services:
  - type: web
    name: morven
    runtime: static
    buildCommand: npm run build
    staticPublishPath: build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: MORVEN_API_URL
        sync: false
